### ISSUE TITLE
01_verify.js

### ISSUE THREAD

**Issue by s74s** [joisadler/test-assignments#1]
Привет !
Твое решение игнорирует закрывающие скобки без пары, эти вызовы вернут '1':
`verify('<>>');`
`verify('[]]');`
`verify('][]');`
P.S. В тестах к заданию не увидел покрытия этих кейсов. Поругай их там за это.

**Comment by joisadler** [comment]
Привет. Только сейчас заметил твой issue. Спасибо за замечание!
Тесты писал я сам на основе примеров, которые приводятся в задании. Такого кейса там действительно не было.
Добавлю тесты на досуге, разберусь и поправлю код.
Ещё раз, спасибо!
